import Grove.Framework
import TestProject.Grove.Generated.«show-option-mapa»
import TestProject.Grove.Generated.«list-array-operations»

/-
This file is autogenerated by grove. You can manually edit it, for example to resolve merge
conflicts, but be careful.
-/

open Grove.Framework Widget

namespace TestProject.Grove.Generated

def restoreState : RestoreStateM Unit := do
  «show-option-mapa».restoreState
  «list-array-operations».restoreState
