import Grove.Framework
import TestProject.Grove.Generated.«no-option-to-vector»
import TestProject.Grove.Generated.«show-option-mapa»
import TestProject.Grove.Generated.«list-array-operations»
import TestProject.Grove.Generated.«list-array-lemmas»

/-
This file is autogenerated by grove. You can manually edit it, for example to resolve merge
conflicts, but be careful.
-/

open Grove.Framework Widget

namespace TestProject.Grove.Generated

def restoreState : RestoreStateM Unit := do
  «no-option-to-vector».restoreState
  «show-option-mapa».restoreState
  «list-array-operations».restoreState
  «list-array-lemmas».restoreState
