// Code generated by jtd-codegen for TypeScript v0.2.1

export type Node = Node0;

export interface Assertion {
  id: string;
  message: string;
  success: boolean;
  title: string;
}

export type Declaration = DeclarationDef | DeclarationMissing | DeclarationThm;

export interface DeclarationDef {
  constructor: "def";
  def: Definition;
}

export interface DeclarationMissing {
  constructor: "missing";
  missing: string;
}

export interface DeclarationThm {
  constructor: "thm";
  thm: Theorem;
}

export interface Definition {
  isDeprecated: boolean;
  name: string;
  renderedStatement: string;
}

export interface FactMetadata {
  comment: string;
  status: FactStatus;
}

export enum FactStatus {
  Bad = "bad",
  BelievedGood = "believedGood",
  Done = "done",
  NothingToDo = "nothingToDo",
  Postponed = "postponed",
}

export type FactValidationResult = FactValidationResultInvalidated | FactValidationResultOk;

export interface FactValidationResultInvalidated {
  constructor: "invalidated";
  invalidated: string;
}

export interface FactValidationResultOk {
  constructor: "ok";
  dummy?: string;
}

export type Node0 = NodeAssertion | NodeNamespace | NodeSection | NodeShowDeclaration | NodeText;

export interface NodeAssertion {
  constructor: "assertion";
  assertion: Assertion;
}

export interface NodeNamespace {
  constructor: "namespace";
  namespace: string;
}

export interface NodeSection {
  constructor: "section";
  section: Section;
}

export interface NodeShowDeclaration {
  constructor: "showDeclaration";
  showDeclaration: ShowDeclaration;
}

export interface NodeText {
  constructor: "text";
  text: string;
}

export interface Section {
  children: Node0[];
  id: string;
  title: string;
}

export interface ShowDeclaration {
  facts: ShowDeclarationFact[];
  id: string;
  name: string;
}

export interface ShowDeclarationFact {
  factId: string;
  metadata: FactMetadata;
  state: Declaration;
  validationResult: FactValidationResult;
}

export interface Theorem {
  isDeprecated: boolean;
  isSimp: boolean;
  name: string;
  renderedStatement: string;
}
