// Code generated by jtd-codegen for TypeScript v0.2.1

export type InvalidatedFacts = InvalidatedFacts0;

export interface InvalidatedFact {
  factId: string;
  widgetId: string;
}

export interface InvalidatedFacts0 {
  invalidatedFacts: InvalidatedFact[];
  needAttentionFacts: InvalidatedFact[];
}
