name = "test-project"
version = "0.1.0"
defaultTargets = ["test-project"]

# Real users will be using `git` and `subDir` instead.
[[require]]
name = "grove"
path = "../backend"

[[lean_lib]]
name = "TestProject"

[[lean_exe]]
name = "test-project"
supportInterpreter = true
root = "Main"
