name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: ./backend

  build-test-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: ./test-project

  grove-test-project:
    runs-on: ubuntu-latest

    steps:
      - uses: TwoFx/grove-action@master
        with:
          project-path: "test-project"
          script-name: "test-project"
